# -*- coding: utf-8 -*-
"""Kidney Disease Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNP89zD_7AXvlUtRO__5afbgSBglCE3z
"""

pip install nltk

pip install newspaper3k

from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#Downloading punkt package
nltk.download('punkt', quiet= True)

#Extracting the article
article=Article('https://www.mayoclinic.org/diseases-conditions/chronic-kidney-disease/symptoms-causes/syc-20354521')
article.download()
article.parse()
article.nlp()
corpus=article.text

#Text printing
print(corpus)

#Tokenisation
text=corpus
sentence_list=nltk.sent_tokenize(text)

print(sentence_list)

#Creating a greeting response
def greeting_response(text):
  text=text.lower()

  bot_greetings=["Howdy", "Hi", "Hey", "Hello", "Hey there"]
  user_greetings=["Hi", "Hey", "Hello", "Wassup"]

  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def index_sort(list_var):
  length=len(list_var)
  list_index= list(range(0, length))
  x= list_var
  
  for i in range(length):
    for j in range(length):
      if x[list_index[i]] > x[list_index[j]]:
        temp=list_index[i]
        list_index[i]=list_index[j]
        list_index[j]=temp
  return list_index

#Bots response
def bot_response(user_input):
  user_input=user_input.lower()
  sentence_list.append(user_input)
  bot_response= ''
  cm=CountVectorizer().fit_transform(sentence_list)
  similarity_scores= cosine_similarity(cm[-1], cm)
  similarity_scores_list= similarity_scores.flatten()
  index= index_sort(similarity_scores_list)
  index= index[1:]
  response_flag= 0

  j=0
  for i in range(len(index)):
    if similarity_scores_list[index[i]]> 0.0:
      bot_response=bot_response+' '+sentence_list[index[i]]
      response_flag=1
      j=j+1
    if j>2:
      break
    
    if response_flag==0:
      bot_response=bot_response+' '+'I dont understand.'
    
    sentence_list.remove(user_input)
    return bot_response

#Starting the chat
print('Dr. Kidney: Hello, I am a doctor for Kidney and I will answer your questions related to chronic kidney disease')

exit_list=['exit', 'see you later', 'bye']
while(True):
  user_input= input()
  if user_input.lower() in exit_list:
    print("Dr Kidney: Talk to you later!!")
    break
  else:
    if greeting_response(user_input) != None:
      print('Dr. Kidney:'+greeting_response(user_input))
    else:
      print('Dr. Kidney: '+bot_response(user_input))